[[plugins]]
repo = 'Shougo/vimproc'
build = 'make'

[[plugins]] repo = 'scrooloose/nerdtree'
hook_add = '''
  noremap <C-e> :NERDTreeToggle<CR>
  filetype plugin indent on
'''
on_i = 1

[[plugins]]
repo = 'Shougo/deoplete.nvim'
hook_add = '''
  let g:deoplete#enable_at_startup   = 1
  let g:deoplete#auto_complete_delay = 0
  let g:deoplete#enable_smart_case = 1
  inoremap <expr><TAB>  pumvisible() ? "\<C-n>" : "\<TAB>"
  set completeopt=menuone
'''
on_i = 1

[[plugins]]
repo = 'roxma/nvim-yarp'

[[plugins]]
repo = 'roxma/vim-hug-neovim-rpc'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'tomtom/tcomment_vim'

[[plugins]]
repo = 'junegunn/vim-easy-align'
hook_add = '''
xmap ga <Plug>(EasyAlign)
nmap ga <Plug>(EasyAlign)
'''

[[plugins]]
repo = 'terryma/vim-multiple-cursors'
hook_source = '''
func! Multiple_cursors_before()
  if deoplete#is_enabled()
    call deoplete#disable()
    let g:deoplete_is_enable_before_multi_cursors = 1
  else
    let g:deoplete_is_enable_before_multi_cursors = 0
  endif
endfunc
func! Multiple_cursors_after()
  if g:deoplete_is_enable_before_multi_cursors
    call deoplete#enable()
  endif
endfunc
'''
on_i = 1

[[plugins]]
repo = 'mattn/emmet-vim'

[[plugins]]
repo = 'elzr/vim-json'
hook_source = '''
  let g:vim_json_syntax_conceal = 0
'''
on_i = 1

[[plugins]]
repo = 'Konfekt/FastFold'
on_i = 1

[[plugins]]
repo = 'Konfekt/FoldText'
on_i = 1

[[plugins]]
repo = 'posva/vim-vue'
on_ft = ['js','vue']
on_i = 1

[[plugins]]
repo = 'fatih/vim-go'
hook_add = '''
  let g:go_fmt_command = "goimports"
  let g:go_highlight_types = 1
  let g:go_highlight_fields = 1
  let g:go_highlight_function_calls = 1
  let g:go_def_mode='gopls'
'''
on_ft = ['go']

[[plugins]]
repo = 'rust-lang/rust.vim'
on_ft = 'rust'
hook_source = '''
  let g:rustfmt_autosave = 0
'''
on_i = 1

[[plugins]]
repo = 'racer-rust/vim-racer'
on_ft = 'rust'
hook_source = '''
  let g:racer_cmd = "~/.cargo/bin/racer"
  let g:racer_experimental_completer = 1
  let $RUST_SRC_PATH="{/Users/naka/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/src/ }"
'''
on_i = 1

[[plugins]]
on_ft = 'typescript'
repo = 'jason0x43/vim-js-indent'
on_i = 1

[[plugins]]
on_ft = 'typescript'
repo = 'mhartington/nvim-typescript'
on_i = 1

[[plugins]]
repo = 'kamykn/spelunker.vim'
hook_add = '''
  set nospell
  let g:enable_spelunker_vim = 1
'''

[[plugins]]
repo = 'zchee/deoplete-go'
on_source = 'deoplete.nvim'
build = 'make'
on_i = 1

[[plugins]]
repo = 'prabirshrestha/async.vim'

[[plugins]]
repo = 'prabirshrestha/vim-lsp'
hook_add = '''
  let g:lsp_diagnostics_enabled = 0

  " debug
  let g:lsp_log_verbose = 1
  let g:lsp_log_file = expand('~/vim-lsp.log')
  let g:asyncomplete_log_file = expand('~/asyncomplete.log')

  augroup LspGo
    au!
    autocmd User lsp_setup call lsp#register_server({
        \ 'name': 'go-lang',
        \ 'cmd': {server_info->['gopls']},
        \ 'whitelist': ['go'],
        \ })
    autocmd FileType go setlocal omnifunc=lsp#complete
    autocmd FileType go nmap <buffer> gd <plug>(lsp-definition)
    autocmd FileType go nmap <buffer> ,n <plug>(lsp-next-error)
    autocmd FileType go nmap <buffer> ,p <plug>(lsp-previous-error)
  augroup END
'''

[[plugins]]
repo = 'prabirshrestha/asyncomplete.vim'

[[plugins]]
repo = 'prabirshrestha/asyncomplete-lsp.vim'

[[plugins]]
repo = 'natebosch/vim-lsc'
hook_add = 'let g:lsp_async_completion = 1'
