name: Ubuntu

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v1

      - name: Setup dotfiles
        run: make init

      - name: Deploy dotfiles
        run: make deploy

      - name: Clean dotfiles
        run: make clean

